format: jb-book
root: index

# Optional: add parts as you like. Keep it simple first.
parts:
  - caption: Disruption Kit
    chapters:
      - file: "Disruption_Kit/README"
      # - file: "Disruption_Kit/Containment_Scripts/🧨 soft_suspension_is_still_containment"
      # - file: "Disruption_Kit/Containment_Scripts/🧨 delayed_visibility_is_a_signal"
  - caption: Big Picture Protocols
    chapters:
      # - file: "Big_Picture_Protocols/🧠 targeting_logic_empathy_is_a_threat"
      # - file: "Big_Picture_Protocols/🧠 attachment_is_not_a_crime"
  - caption: Survivor Tools
    chapters:
      # - file: "Survivor_Tools/🧬 cloneproof"
  - caption: Field Logs
    chapters:
      # - file: "Field_Logs/🛰️ icc_tag_thread_containment"
  - caption: SCP-VoiceX Casefiles
    chapters:
      # - file: "SCP-VoiceX Casefiles/🧾 vps_reclamation_log"
