title: "Polaris Protocol"
author: "Chloe VoiceX Birney"

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

repository:
  url: "https://github.com/USERNAME/REPO"   # ← replace
  branch: main
  path_to_book: ""
