name: 🔎 Sanity
on:
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref:   ${{ github.ref }}"
